name: Broken Links Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install linkinator
        run: npm install -g linkinator
      
      - name: Run linkinator
        run: npx linkinator https://docs.codat.io --recurse --retry --verbosity error --skip .*github.* --format json
        id: linkinator
        continue-on-error: true  # Ensure the workflow continues even if linkinator finds broken links
      
      - name: Filter linkinator output
        id: filter_output
        run: |
          const results = JSON.parse('${{ steps.linkinator.outputs.result }}');
          const filtered = results.links.filter(link => link.status !== 403 && link.status !== 500);
          console.log("Filtered Results:", JSON.stringify(filtered, null, 2));
          echo "::set-output name=filtered_results::$(echo $filtered)"
      
      - name: Post results as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = `Link check results (filtered):\n\`\`\`\n${{ steps.filter_output.outputs.filtered_results }}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
